jobs:
  - job: Windows
    pool: "Hosted VS2017"

    variables:
      os_name: Windows

    strategy:
      matrix:
        node_12_x:
          node_version: 12.x
        node_13_x:
          node_version: 13.x
        node_14_x:
          node_version: 14.x
        node_15_x:
          node_version: 15.x
    steps:
      - template: azure-test.yml

  - job: Linux
    pool:
      vmImage: "ubuntu-latest"

    variables:
      os_name: Linux

    strategy:
      matrix:
        node_12_x:
          node_version: 12.x
        node_13_x:
          node_version: 13.x
        node_14_x:
          node_version: 14.x
        node_15_x:
          node_version: 15.x

    steps:
      - template: azure-test.yml

  - job: OSX
    pool:
      vmImage: "macOS-latest"

    variables:
      os_name: OSX

    strategy:
      matrix:
        node_12_x:
          node_version: 12.x
        node_13_x:
          node_version: 13.x
        node_14_x:
          node_version: 14.x
        node_15_x:
          node_version: 15.x

    steps:
      - template: azure-test.yml
